apiVersion: apps/v1
kind: Deployment
metadata:
  name: IDP
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: IDP
  template:
    metadata:
      labels:
        app: IDP
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: IDP
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
